// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || '';

// Export the anon key for use in Edge Function calls
export const SUPABASE_ANON_KEY = SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Only create client if we have valid credentials
// This prevents errors during build and provides better runtime error handling
export const supabase = (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY && 
  SUPABASE_URL !== 'https://placeholder.supabase.co' && 
  SUPABASE_PUBLISHABLE_KEY !== 'placeholder-key')
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: typeof window !== 'undefined' ? window.localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : null as any; // Type assertion for build - will be properly initialized at runtime with env vars
